# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c65794ed4b60e8c14f1c458c67c96169eb4e002bc4a758074fb38e19c2e39d1f6dc854b7217ea2c2aa17fdfd238f56bab5c5931cdff3cc54231c35e855ed732d

test:
  secret_key_base: 339286641ffc7b9899ea3382637c43171ab7bfa4838b660955b13deb5e9969e0669ba851af8d479e83dce491f70b685fd807c07b71db79b72e2ede5e122c4fb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
